// Generated by Tools/CalibrateConstructionLoudness.py; do not edit by hand.
// Output level references that bring every construction and Picking to
// the default construction's integrated loudness (Original model,
// Dreadnought, Spruce, Finger, on the stereo microphones), each capture on
// its own (Docs/decisions.md, 2026-09-29, "Every construction as loud as
// the default"). A cell is
//   ((model * 4 + shape) * 3 + wood) * 3 + picking
// in the enums' order in AcustraEngine.h.
#pragma once

#include <array>

namespace acustra::detail
{
// The factor on the output reference (outputReferenceFor).
inline constexpr std::array<float, 72> constructionMicReference {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    1.2097348f, 1.14131534f, 1.21941197f, 1.32905376f, 1.25076175f, 1.33901119f, 1.25761497f, 1.09277272f, 1.2847476f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    1.40079939f, 1.03257465f, 1.47103846f, 1.47659469f, 1.1234206f, 1.54317331f, 1.49411106f, 1.10223007f, 1.57129788f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.0f, 0.873527586f, 0.994848132f, 1.09800088f, 0.971913218f, 1.09930122f, 1.08095527f, 0.928274333f, 1.08121014f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    0.918383718f, 0.746266007f, 0.943378448f, 0.985351205f, 0.801904023f, 1.02372015f, 0.878137589f, 0.737959743f, 0.88831681f,
    // bellido1978 parlor: spruce, mahogany, maple x finger, pick, thumb
    2.36652875f, 1.23801959f, 2.78730774f, 2.59075713f, 1.40143085f, 3.01983714f, 2.6006608f, 1.26321685f, 3.01673222f,
    // bellido1978 auditorium: spruce, mahogany, maple x finger, pick, thumb
    2.18781376f, 1.13808703f, 2.52172875f, 2.51820326f, 1.33512926f, 2.88358378f, 2.20656848f, 1.10525608f, 2.56624556f,
    // bellido1978 dreadnought: spruce, mahogany, maple x finger, pick, thumb
    2.05382967f, 0.992671013f, 2.35237384f, 2.17823958f, 1.12491488f, 2.47041249f, 2.0957706f, 1.00846708f, 2.50931025f,
    // bellido1978 jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.65448475f, 0.846913815f, 1.89774394f, 1.89737976f, 0.944638908f, 2.18260241f, 1.52966928f, 0.845702767f, 1.7303251f
}};
// The mono microphone's factor over constructionMicReference.
inline constexpr std::array<float, 72> constructionMonoTrim {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    0.992117703f, 0.983805895f, 0.992500067f, 0.999380052f, 0.992260098f, 0.994536579f, 0.97882247f, 0.956545949f, 0.980612755f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    1.01925004f, 1.06956482f, 1.03003037f, 1.02068448f, 1.08349383f, 1.02352905f, 1.01392829f, 1.06278872f, 1.01657844f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.0f, 0.973712623f, 1.02762914f, 1.03464794f, 0.993837059f, 1.04020727f, 1.02575231f, 0.950345337f, 1.03257358f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.00161004f, 0.978765666f, 1.01170659f, 0.997135341f, 0.987119496f, 1.00992441f, 1.02585971f, 0.989910245f, 1.02696979f,
    // bellido1978 parlor: spruce, mahogany, maple x finger, pick, thumb
    0.924620569f, 0.934912801f, 0.884033859f, 0.915860236f, 0.943818569f, 0.880946517f, 0.937091231f, 0.928453088f, 0.917313516f,
    // bellido1978 auditorium: spruce, mahogany, maple x finger, pick, thumb
    0.977121592f, 1.01023853f, 0.978736758f, 0.961280346f, 0.896632671f, 0.957519352f, 0.979999006f, 0.953766465f, 0.971830487f,
    // bellido1978 dreadnought: spruce, mahogany, maple x finger, pick, thumb
    0.998933315f, 0.863867164f, 0.99211067f, 1.00591278f, 0.868212163f, 0.995092809f, 1.01427591f, 0.872099936f, 0.999017477f,
    // bellido1978 jumbo: spruce, mahogany, maple x finger, pick, thumb
    0.984130681f, 0.958891749f, 0.987461805f, 0.999878824f, 0.885755658f, 1.0006572f, 0.995210052f, 0.874284148f, 0.970853984f
}};
// The piezo's factor over constructionMicReference, on its own trim
// (PiezoDesign::trim).
inline constexpr std::array<float, 72> constructionPiezoTrim {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    1.33485675f, 0.708083808f, 1.47473824f, 1.220433f, 0.647295475f, 1.34892178f, 1.2752496f, 0.740974545f, 1.39389968f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    1.14454007f, 0.785708725f, 1.21498561f, 1.08485079f, 0.722795188f, 1.15852737f, 1.07055438f, 0.728536308f, 1.12956274f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.61705124f, 0.939041197f, 1.80608463f, 1.47448468f, 0.841173112f, 1.63708544f, 1.47886753f, 0.867637753f, 1.64576864f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.76981151f, 1.09320056f, 1.92129242f, 1.66952789f, 1.02370226f, 1.792382f, 1.84512246f, 1.10530365f, 2.02493024f,
    // bellido1978 parlor: spruce, mahogany, maple x finger, pick, thumb
    0.731063306f, 0.732798517f, 0.669701338f, 0.672773182f, 0.6479972f, 0.620457411f, 0.662479043f, 0.710641682f, 0.615038574f,
    // bellido1978 auditorium: spruce, mahogany, maple x finger, pick, thumb
    0.792216241f, 0.800060153f, 0.741152704f, 0.692357898f, 0.686251938f, 0.649731398f, 0.784097254f, 0.821028292f, 0.725561917f,
    // bellido1978 dreadnought: spruce, mahogany, maple x finger, pick, thumb
    0.855575442f, 0.930277407f, 0.802610517f, 0.812084913f, 0.822896421f, 0.767322421f, 0.836607277f, 0.916464031f, 0.74702841f,
    // bellido1978 jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.05233169f, 1.08303773f, 0.985706031f, 0.922739685f, 0.979310036f, 0.860664964f, 1.13493979f, 1.08231246f, 1.08223248f
}};
} // namespace acustra::detail
