// Generated by Tools/CalibrateConstructionLoudness.py; do not edit by hand.
// Output level references that bring every construction and Picking to
// the default construction's integrated loudness (Dreadnought, Spruce,
// Finger, on the stereo microphones), each capture on its own
// (Docs/decisions.md, 2026-09-29, "Every construction as loud as the
// default"). A cell is
//   (shape * 3 + wood) * 3 + picking
// in the enums' order in AcustraEngine.h.
#pragma once

#include <array>

namespace acustra::detail
{
// The factor on the output reference (outputReferenceFor).
inline constexpr std::array<float, 36> constructionMicReference {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    0.760610819f, 0.470330745f, 0.771966398f, 0.820821464f, 0.528591037f, 0.83477354f, 0.746397197f, 0.418025106f, 0.763453364f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    0.966414273f, 0.475679755f, 1.00756371f, 1.05571544f, 0.553628325f, 1.0869689f, 1.0073725f, 0.493330002f, 1.04388583f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.0f, 0.490869612f, 1.0368433f, 1.07848358f, 0.569059312f, 1.11828709f, 1.03953743f, 0.48039028f, 1.08366895f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    0.916526496f, 0.472167522f, 0.943059385f, 0.984209418f, 0.548398435f, 1.01947093f, 0.985725284f, 0.48146069f, 1.01641726f
}};
// The mono microphone's factor over constructionMicReference.
inline constexpr std::array<float, 36> constructionMonoTrim {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    0.958914042f, 0.836784184f, 0.951475143f, 0.960529268f, 0.846171081f, 0.950459242f, 0.950775921f, 0.806001902f, 0.934207857f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    0.900219262f, 0.740158021f, 0.869367659f, 0.905392349f, 0.741840243f, 0.882662833f, 0.912682474f, 0.75526011f, 0.889950275f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.0f, 0.757810235f, 0.907291174f, 0.934359848f, 0.786852241f, 0.925611138f, 0.888785064f, 0.735073328f, 0.889690161f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    0.921939194f, 0.792845011f, 0.912415504f, 0.928752184f, 0.807761788f, 0.918456137f, 0.917940855f, 0.766977251f, 0.898364365f
}};
// The piezo's factor over constructionMicReference, on its own trim
// (PiezoDesign::trim).
inline constexpr std::array<float, 36> constructionPiezoTrim {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    1.74242187f, 1.18122923f, 1.80150056f, 1.61880779f, 1.05210555f, 1.66935742f, 1.77710724f, 1.3451283f, 1.82515454f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    1.3306886f, 1.16687667f, 1.33868027f, 1.23425627f, 1.00787342f, 1.25571048f, 1.26488829f, 1.12328315f, 1.27663958f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.33182549f, 1.14165938f, 1.34931123f, 1.23795497f, 0.9832564f, 1.25156343f, 1.25996423f, 1.15683043f, 1.27347887f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.47231388f, 1.22373676f, 1.50143373f, 1.38299453f, 1.04932487f, 1.39726007f, 1.35010922f, 1.16059971f, 1.37185907f
}};
} // namespace acustra::detail
