// Generated by Tools/CalibrateConstructionLoudness.py; do not edit by hand.
// Output level references that bring every construction and Picking to
// the default construction's integrated loudness (Original model,
// Dreadnought, Spruce, Finger, on the stereo microphones), each capture on
// its own (Docs/decisions.md, 2026-09-29, "Every construction as loud as
// the default"). A cell is
//   ((model * 4 + shape) * 3 + wood) * 3 + picking
// in the enums' order in AcustraEngine.h.
#pragma once

#include <array>

namespace acustra::detail
{
// The factor on the output reference (outputReferenceFor).
inline constexpr std::array<float, 72> constructionMicReference {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    0.739936531f, 0.651179433f, 0.73681277f, 0.846723855f, 0.739614487f, 0.842548013f, 0.797313213f, 0.649446726f, 0.802507222f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    1.31605518f, 0.786953986f, 1.38714767f, 1.40291989f, 0.898209453f, 1.46137512f, 1.36893129f, 0.824041724f, 1.4250648f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.0f, 0.622051954f, 1.02834225f, 1.08948255f, 0.714138925f, 1.11591899f, 1.09168804f, 0.631926239f, 1.13752913f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    0.891506672f, 0.5343135f, 0.920666754f, 0.972916842f, 0.606339514f, 1.01304054f, 0.861815035f, 0.528717875f, 0.879646719f,
    // bellido1978 parlor: spruce, mahogany, maple x finger, pick, thumb
    2.35056925f, 1.22118509f, 2.75932121f, 2.56945539f, 1.3835206f, 2.99418426f, 2.57858253f, 1.24648893f, 2.99009466f,
    // bellido1978 auditorium: spruce, mahogany, maple x finger, pick, thumb
    2.16330194f, 1.12308633f, 2.50132513f, 2.50120473f, 1.31695843f, 2.85626078f, 2.18835092f, 1.09176028f, 2.54424191f,
    // bellido1978 dreadnought: spruce, mahogany, maple x finger, pick, thumb
    2.04000568f, 0.983093381f, 2.33670616f, 2.16264987f, 1.11350036f, 2.45327091f, 2.08289528f, 0.95807606f, 2.49741626f,
    // bellido1978 jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.6394701f, 0.836779714f, 1.88140857f, 1.88071597f, 0.931971669f, 2.16407704f, 1.51637053f, 0.794391274f, 1.71605456f
}};
// The mono microphone's factor over constructionMicReference.
inline constexpr std::array<float, 72> constructionMonoTrim {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    0.984402418f, 0.953968883f, 0.992411375f, 0.979837954f, 0.949320555f, 0.989237785f, 0.973634601f, 0.937091053f, 0.97426039f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    0.977002323f, 0.799538076f, 0.986418068f, 0.984869719f, 0.825228214f, 0.996200085f, 0.983249366f, 0.822128892f, 1.00146186f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.0f, 0.842918277f, 1.01892185f, 1.00378823f, 0.878948748f, 1.027264f, 0.955891252f, 0.772232533f, 0.994467914f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    0.9860605f, 0.875197589f, 1.00306344f, 0.992504001f, 0.844985604f, 1.00421369f, 0.997599363f, 0.844210684f, 1.01878643f,
    // bellido1978 parlor: spruce, mahogany, maple x finger, pick, thumb
    0.922377765f, 0.935119033f, 0.88494432f, 0.915127635f, 0.942589521f, 0.880611837f, 0.935782492f, 0.926911294f, 0.916589677f,
    // bellido1978 auditorium: spruce, mahogany, maple x finger, pick, thumb
    0.978916168f, 0.909334958f, 0.977684081f, 0.958836913f, 0.896668911f, 0.958145857f, 0.978373945f, 0.918621004f, 0.970475912f,
    // bellido1978 dreadnought: spruce, mahogany, maple x finger, pick, thumb
    0.998104632f, 0.863828719f, 0.994671524f, 1.00516975f, 0.868079484f, 0.996169806f, 1.0132091f, 0.886260331f, 0.999800086f,
    // bellido1978 jumbo: spruce, mahogany, maple x finger, pick, thumb
    0.981124222f, 0.875773191f, 0.988085508f, 0.998302579f, 0.885755122f, 0.998040676f, 0.992663085f, 0.829570174f, 0.970128715f
}};
// The piezo's factor over constructionMicReference, on its own trim
// (PiezoDesign::trim).
inline constexpr std::array<float, 72> constructionPiezoTrim {{
    // original parlor: spruce, mahogany, maple x finger, pick, thumb
    2.18637371f, 1.24238622f, 2.44501686f, 1.91667593f, 1.09566045f, 2.1443212f, 2.01289392f, 1.24479628f, 2.23345375f,
    // original auditorium: spruce, mahogany, maple x finger, pick, thumb
    1.21912146f, 1.03227603f, 1.28934753f, 1.14267111f, 0.905168235f, 1.22594106f, 1.16921854f, 0.973945081f, 1.24804962f,
    // original dreadnought: spruce, mahogany, maple x finger, pick, thumb
    1.61847818f, 1.31997299f, 1.74893653f, 1.48736799f, 1.14596343f, 1.61428702f, 1.46539414f, 1.27569318f, 1.5654856f,
    // original jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.82428634f, 1.52789271f, 1.96997535f, 1.69193959f, 1.35498428f, 1.81251919f, 1.88130724f, 1.5438453f, 2.0463388f,
    // bellido1978 parlor: spruce, mahogany, maple x finger, pick, thumb
    0.731367826f, 0.737951815f, 0.672458708f, 0.674055934f, 0.652024031f, 0.622927248f, 0.663912356f, 0.715286016f, 0.61682874f,
    // bellido1978 auditorium: spruce, mahogany, maple x finger, pick, thumb
    0.796175182f, 0.805425882f, 0.742827892f, 0.692709804f, 0.69116199f, 0.652114332f, 0.78571552f, 0.825545311f, 0.727563918f,
    // bellido1978 dreadnought: spruce, mahogany, maple x finger, pick, thumb
    0.85573566f, 0.932788372f, 0.80305928f, 0.813812852f, 0.825602591f, 0.768001378f, 0.836201966f, 0.959465325f, 0.745980144f,
    // bellido1978 jumbo: spruce, mahogany, maple x finger, pick, thumb
    1.05505097f, 1.08842099f, 0.988190293f, 0.924867928f, 0.98571831f, 0.862735927f, 1.1375072f, 1.1440289f, 1.084674f
}};
} // namespace acustra::detail
