// Generated by Tools/GenerateMeasuredBridge.py; do not hand-edit.
// Passive spatial approximations fitted to each guitar's bass and treble
// impacts and two accelerometers behind the saddle (Method.pdf Fig. 3).
// Sensor spacing is unreported; treating the responses as collocated ports
// is a model assumption. The cross-record corner is heuristic, not a unique
// measurement of lost rigidity. Acceleration/
// force is converted to velocity/force by differentiating the hammer,
// following the archive script. The model uses heaving and normalized
// rocking displacement r=a*theta; distance along the saddle is in
// units of the impact half-separation a, so impacts are at u = -1 (bass) and
// u = +1 (treble) and a string at u sees
//     Y(u) = sum over modes of (heave + 2 u cross + u^2 rock)
//                              * s/(s^2 + 2 damping s + omega^2),
// which fits the treble-side response at u = +1 and bass-side at u = -1.
// Each mode's residue matrix [[heave, cross], [cross, rock]] is positive
// semidefinite, so the model's Y(u) is positive real. This constraint does
// not establish passivity or collocation of the measured response matrix.
// The Original model plays g21, a measured flamenco guitar adapted for steel
// strings.
// Adapted from Robert Mores, "Archive for the acoustical documentation of
// classical Spanish guitars, flamenco guitars and romantic guitars from
// private and public collections -- bridge mobility" (2021),
// https://doi.org/10.5281/zenodo.4604577, licensed CC BY 4.0; see
// THIRD_PARTY_NOTICES.md.

#pragma once

#include <array>
#include <cstdint>

namespace acustra::detail
{
struct MeasuredBridgeMode
{
    float frequency;
    float q;
    float heave;
    float cross;
    float rock;
};

// g21, a 2018 Lester DeVoe flamenca blanca, spruce/cypress, measured in a
// school music room in Freiburg. A positive-semidefinite least-squares
// projection retained 47 of 65 measured modal candidates after a 2-sample
// instrumentation alignment; 30 of them carry a rocking residue, the rest
// sitting above the 2245 Hz heuristic corner from the two cross-side
// records' disagreement. Over the six model string positions and 60--10000
// Hz, relative complex error 0.198546 and worst median magnitude error
// 1.262650 dB.
inline constexpr std::array<MeasuredBridgeMode, 47> measuredSteelBridgeModes {{
    { 82.7636719f, 16.3791466f, 2.52597451f, -0.102906391f, 0.00419233274f },
    { 90.8203125f, 21.1919231f, 3.44154811f, -0.196920663f, 0.0112675298f },
    { 178.710938f, 18.1869926f, 11.8324451f, -1.36978376f, 0.158573106f },
    { 208.740234f, 40.9126701f, 0.714238763f, 1.36591911f, 5.97370577f },
    { 371.337891f, 5.60255909f, 1.13691723f, -0.0602727421f, 0.00319531048f },
    { 412.353516f, 37.4513245f, 1.62417686f, -0.0631754696f, 0.00245733093f },
    { 484.130859f, 44.6993484f, 3.15256786f, -0.127928257f, 0.00519120879f },
    { 517.822266f, 31.2370129f, 1.49473441f, -0.130525053f, 0.0113978703f },
    { 591.064453f, 73.0299301f, 1.02562523f, 0.138171479f, 1.64789462f },
    { 656.25f, 65.3659592f, 0.0405622572f, 0.312703073f, 2.4106946f },
    { 728.759766f, 52.9704094f, 2.21863699f, -0.474539399f, 0.101498187f },
    { 766.113281f, 58.0559807f, 0.422612965f, 0.0636353269f, 0.962002277f },
    { 793.212891f, 38.5703545f, 1.02933764f, -0.168583289f, 0.0276103057f },
    { 848.144531f, 8.3443079f, 2.1730051f, 0.0514490269f, 0.623455763f },
    { 867.919922f, 41.790947f, 0.0172690544f, 0.147774011f, 1.26452553f },
    { 919.921875f, 33.1099892f, 0.980685055f, 0.159902915f, 0.0614171959f },
    { 955.078125f, 7.00245142f, 0.389265567f, 0.160490215f, 0.0661684722f },
    { 1032.71484f, 43.4472809f, 1.77797008f, -0.141775191f, 0.0130361067f },
    { 1084.7168f, 26.8180923f, 4.72721958f, -0.450282276f, 0.0428907759f },
    { 1269.28711f, 74.6931534f, 0.10973151f, 0.0750771314f, 0.0513669737f },
    { 1330.81055f, 35.4402084f, 0.0595704839f, -0.598575294f, 6.01459599f },
    { 1374.75586f, 56.8241386f, 0.32936722f, 0.0612278357f, 4.1428318f },
    { 1466.30859f, 24.3766499f, 1.35070062f, -0.155843198f, 4.52854013f },
    { 1697.75391f, 6.26817656f, 2.66874242f, -0.181137368f, 0.0122944592f },
    { 1762.93945f, 32.1352158f, 0.148677945f, 0.0314575061f, 0.130737364f },
    { 1899.90234f, 6.17852879f, 1.79859805f, -0.693352222f, 2.50423884f },
    { 1988.52539f, 13.1727295f, 3.11674571f, 0.335056216f, 2.27330208f },
    { 2054.44336f, 7.01390505f, 0.914667606f, 0.0726630241f, 0.00577249611f },
    { 2149.6582f, 7.25377226f, 2.23036861f, 0.213928521f, 0.0205192138f },
    { 2244.14062f, 32.5072021f, 2.66161275f, 0.179692417f, 0.0121315047f },
    { 2341.55273f, 36.0058975f, 1.21546543f, 0.0f, 0.0f },
    { 3209.47266f, 14.482913f, 3.53973317f, 0.0f, 0.0f },
    { 3551.51367f, 59.3911057f, 0.0929317027f, 0.0f, 0.0f },
    { 3722.16797f, 18.1428795f, 3.66621709f, 0.0f, 0.0f },
    { 4039.30664f, 8.26392746f, 0.0948417261f, 0.0f, 0.0f },
    { 4189.45312f, 8.96288586f, 0.690806568f, 0.0f, 0.0f },
    { 4354.98047f, 20.0971279f, 2.52758908f, 0.0f, 0.0f },
    { 4765.13672f, 6.21177387f, 1.52793574f, 0.0f, 0.0f },
    { 4951.9043f, 9.08312416f, 9.03742123f, 0.0f, 0.0f },
    { 5417.72461f, 10.8632631f, 8.43281174f, 0.0f, 0.0f },
    { 5691.65039f, 27.522274f, 1.27656293f, 0.0f, 0.0f },
    { 6065.91797f, 6.10119963f, 6.22871161f, 0.0f, 0.0f },
    { 6317.13867f, 13.6069679f, 1.93027544f, 0.0f, 0.0f },
    { 6756.5918f, 5.71399689f, 18.6041355f, 0.0f, 0.0f },
    { 7551.26953f, 5.1309967f, 47.6505737f, 0.0f, 0.0f },
    { 8229.49219f, 5.20765686f, 0.668715119f, 0.0f, 0.0f },
    { 9120.11719f, 4.91801691f, 19.0153008f, 0.0f, 0.0f },
}};

// Steel's own bridge on its radiation's poles. 18 of the 47 g21 bridge
// modes are the same resonance as a mode of measuredSteelBodyModes
// (MeasuredBodyData.h): the nearest one, inside its as-fitted half-power
// band, with the bridge mode narrower than the radiation bank's local
// spacing; each takes that mode's engine pole. The others (-1) keep their
// own frequency and take the plate-Q rule's octave factor on their Q
// (GenerateBodyForcePair.py, median of the anechoic flamencas over g21's
// own, never raising, 1 outside its band). steelTopMobilityRatio brings the
// flamenca's mobility to a steel-string guitar's: the geometric mean over
// 80 Hz-4 kHz of |Y| of the Fylde Falstaff
// (Carcagno, Bucknall, Woodhouse, Fritz and Plack, JASA 144 (2018) 3533,
// https://doi.org/10.1121/1.5084735, data https://osf.io/f4pqa/, CC BY 4.0)
// over g21's at u = -1, 0.27406, to three figures; over other bands and
// conductance it spans 0.232-0.301.
inline constexpr float steelTopMobilityRatio = 0.274f;
inline constexpr std::array<std::int16_t, 47> steelBridgeRadiationTwins {{
    -1, 0, 1, 2, -1, 5, 6, 7, 8, 9, 10, 11, 12, -1, 14, 15, -1, 17, 19, -1,
    21, 22, -1, -1, -1, -1, -1, -1, -1, -1, 39, -1, -1, -1, -1, -1, -1, -1,
    -1, -1, -1, -1, -1, -1, -1, -1, -1
}};
inline constexpr std::array<float, 47> steelBridgeUnpairedQRatio {{
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    0.675680399f,
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    1.0f,
    0.814062834f,
    1.0f,
    1.0f,
    0.801757932f,
    1.0f,
    1.0f,
    0.788220286f,
    1.0f,
    1.0f,
    0.844318807f,
    0.856214464f,
    0.853504479f,
    0.901469469f,
    0.872089446f,
    0.881033897f,
    0.880816221f,
    0.900976896f,
    1.0f,
    0.875701725f,
    0.857225478f,
    0.830740511f,
    0.852900386f,
    0.873275042f,
    0.88263303f,
    0.876568675f,
    0.881898165f,
    0.854757488f,
    0.853785634f,
    0.882313251f,
    0.891320467f,
    0.904469013f,
    0.905237675f,
    0.895353615f,
    0.88925904f,
}};
} // namespace acustra::detail
