// Protocol: protocol-v1.md. Independently derived 13-coordinate numerical audit.
#define main frozen_prototype_main
#include "frozen-prototype.cpp"
#undef main
#include <complex>
#include <functional>
#include <memory>

namespace port
{
constexpr int N=13, Q=12;
constexpr double pi=std::numbers::pi;
using V=std::array<double,N>;
using M=std::array<double,N*N>;
using CV=std::array<std::complex<double>,N>;
using CM=std::array<std::complex<double>,N*N>;
double& at(M& a,int i,int j){return a[i*N+j];}
double at(const M& a,int i,int j){return a[i*N+j];}
double dot(const V&a,const V&b){double s=0;for(int i=0;i<N;++i)s+=a[i]*b[i];return s;}
V mv(const M&a,const V&b){V r{};for(int i=0;i<N;++i)for(int j=0;j<N;++j)r[i]+=at(a,i,j)*b[j];return r;}
double quad(const M&a,const V&b){return dot(b,mv(a,b));}
M add(const M&a,const M&b,double scale=1){M r=a;for(int i=0;i<N*N;++i)r[i]+=scale*b[i];return r;}
M scale(const M&a,double x){M r=a;for(auto&v:r)v*=x;return r;}
M chol(const M&a){M l{};for(int i=0;i<N;++i)for(int j=0;j<=i;++j){double x=at(a,i,j);for(int k=0;k<j;++k)x-=at(l,i,k)*at(l,j,k);if(i==j){if(!(x>0&&std::isfinite(x)))throw std::runtime_error("matrix not positive definite");at(l,i,j)=std::sqrt(x);}else at(l,i,j)=x/at(l,j,j);}return l;}
V solveChol(const M&l,const V&b){V y{},x{};for(int i=0;i<N;++i){double s=b[i];for(int j=0;j<i;++j)s-=at(l,i,j)*y[j];y[i]=s/at(l,i,i);}for(int i=N-1;i>=0;--i){double s=y[i];for(int j=i+1;j<N;++j)s-=at(l,j,i)*x[j];x[i]=s/at(l,i,i);}return x;}
M inverse(const M&a){M r{},l=chol(a);for(int j=0;j<N;++j){V e{};e[j]=1;auto x=solveChol(l,e);for(int i=0;i<N;++i)at(r,i,j)=x[i];}return r;}
V eigenvalues(M a){double maximum=0;for(int i=0;i<N;++i)maximum=std::max(maximum,std::abs(at(a,i,i)));for(int sweep=0;sweep<100;++sweep){double off=0;for(int p=0;p<N;++p)for(int q=p+1;q<N;++q){double apq=at(a,p,q);off=std::max(off,std::abs(apq));if(std::abs(apq)<1e-15*maximum)continue;double tau=(at(a,q,q)-at(a,p,p))/(2*apq),t=std::copysign(1.0,tau)/(std::abs(tau)+std::sqrt(1+tau*tau)),c=1/std::sqrt(1+t*t),s=t*c,app=at(a,p,p),aqq=at(a,q,q);for(int k=0;k<N;++k)if(k!=p&&k!=q){double akp=at(a,k,p),akq=at(a,k,q);at(a,k,p)=at(a,p,k)=c*akp-s*akq;at(a,k,q)=at(a,q,k)=s*akp+c*akq;}at(a,p,p)=app-t*apq;at(a,q,q)=aqq+t*apq;at(a,p,q)=at(a,q,p)=0;}if(off<1e-13*maximum)break;}
V r{};for(int i=0;i<N;++i)r[i]=at(a,i,i);std::sort(r.begin(),r.end());return r;}
V generalEigen(const M&mass,const M&stiffness){auto l=chol(mass);M il{};for(int j=0;j<N;++j)for(int i=0;i<N;++i){double s=i==j?1:0;for(int k=0;k<i;++k)s-=at(l,i,k)*at(il,k,j);at(il,i,j)=s/at(l,i,i);}M temp{},b{};for(int i=0;i<N;++i)for(int j=0;j<N;++j)for(int k=0;k<N;++k)at(temp,i,j)+=at(il,i,k)*at(stiffness,k,j);for(int i=0;i<N;++i)for(int j=0;j<N;++j)for(int k=0;k<N;++k)at(b,i,j)+=at(temp,i,k)*at(il,j,k);return eigenvalues(b);}
CV solveComplex(CM a,CV b){for(int k=0;k<N;++k){int p=k;for(int i=k+1;i<N;++i)if(std::abs(a[i*N+k])>std::abs(a[p*N+k]))p=i;if(std::abs(a[p*N+k])<1e-30)throw std::runtime_error("singular complex resolvent");for(int j=k;j<N;++j)std::swap(a[k*N+j],a[p*N+j]);std::swap(b[k],b[p]);for(int i=k+1;i<N;++i){auto f=a[i*N+k]/a[k*N+k];for(int j=k;j<N;++j)a[i*N+j]-=f*a[k*N+j];b[i]-=f*b[k];}}CV x{};for(int i=N-1;i>=0;--i){auto s=b[i];for(int j=i+1;j<N;++j)s-=a[i*N+j]*x[j];x[i]=s/a[i*N+i];}return x;}
std::string num(double x){return std::isfinite(x)?experiment::number(x):"null";}
std::string vec(const V&v){std::string s="[";for(int i=0;i<N;++i)s+=(i?",":"")+num(v[i]);return s+"]";}
std::string mat(const M&m){std::string s="[";for(int i=0;i<N*N;++i)s+=(i?",":"")+num(m[i]);return s+"]";}
std::string complexJson(std::complex<double>x){return "["+num(x.real())+","+num(x.imag())+"]";}

struct Model
{
 experiment::Model old;
 bool nonlinear;
 double m,L,mu,G,mb=.05,kb,cb;
 M Ms{},Ks{},mass{},K{},Minv{};
 V d{},b{};
 Model(bool exact):old(exact?experiment::Potential::exact:experiment::Potential::linear),nonlinear(exact),m(old.mass),L(old.physical.length),mu(old.physical.density),G(old.physical.axial-old.physical.tension),kb(mb*std::pow(2*pi*220,2)),cb(mb*2*pi*220/30)
 {
  for(int n=0;n<Q;++n){d[n]=2/(L*old.waveNumber[n]);at(Ms,n,n)=m;at(Ms,n,Q)=at(Ms,Q,n)=m*d[n];at(Ks,n,n)=old.stiffness[n];b[n]=old.forceShape[n];}
  at(Ms,Q,Q)=mu*L/3;at(Ks,Q,Q)=old.physical.tension/L;b[Q]=.827;
  mass=Ms;at(mass,Q,Q)+=mb;K=Ks;at(K,Q,Q)+=kb;Minv=inverse(mass);
 }
 M damping(double eta,bool body)const{M c=scale(Ms,2*eta);if(body)at(c,Q,Q)+=cb;return c;}
 double potential(const V&z,V*gradient=nullptr,M*hessian=nullptr)const{
  if(gradient)gradient->fill(0);if(hessian)hessian->fill(0);if(!nonlinear)return 0;
  double phi=0;for(int i=0;i<=old.intervals;++i){V row{};for(int n=0;n<Q;++n)row[n]=old.slopeMatrix[i*Q+n];row[Q]=-1/L;double s=dot(row,z),square=s*s,root=std::sqrt(1+square),strain=square/(root+1),tau=G*strain*s/root,w=old.weights[i];phi+=w*G*strain*strain/2;if(gradient)for(int n=0;n<N;++n)(*gradient)[n]+=w*tau*row[n];if(hessian){double dtau=G*square*(root*root+root+1)/(std::pow(root,3)*(root+1));for(int n=0;n<N;++n)for(int j=0;j<N;++j)at(*hessian,n,j)+=w*dtau*row[n]*row[j];}}
  return phi;
 }
 V pluck(double amplitude)const{auto q=old.pluck(amplitude);V z{};std::copy(q.begin(),q.end(),z.begin());return z;}
 double pointForce(const V&z)const{double s=-z[Q]/L,f=0;for(int n=0;n<Q;++n){double k=old.waveNumber[n];s+=k*z[n];f+=old.physical.bending*k*k*k*z[n];}f+=old.physical.tension*s;if(nonlinear){double r=std::sqrt(1+s*s);f+=G*s*s/(r+1)*s/r;}return f;}
 V acceleration(const V&z,const V&v,double force,const M&c,const M&invMass)const{V grad{},rhs{};potential(z,&grad);auto kz=mv(K,z),cv=mv(c,v);for(int n=0;n<N;++n)rhs[n]=b[n]*force-kz[n]-cv[n]-grad[n];return mv(invMass,rhs);}
 double physicalEnergy(const V&z,const V&v)const{return .5*quad(mass,v)+.5*quad(K,z)+potential(z);}
 V equilibrium(double force,int&iterations,double&residual,double&minHessian)const{
  V rhs{};for(int n=0;n<N;++n)rhs[n]=b[n]*force;V z=solveChol(chol(K),rhs);double norm=std::sqrt(dot(rhs,rhs));
  for(iterations=0;iterations<40;++iterations){V grad{};M hes{};double phi=potential(z,&grad,&hes);auto kz=mv(K,z);V r{};for(int n=0;n<N;++n)r[n]=kz[n]+grad[n]-rhs[n];residual=std::sqrt(dot(r,r))/norm;M h=add(K,hes);minHessian=eigenvalues(h)[0];if(residual<1e-12)return z;auto step=solveChol(chol(h),r);double energy=.5*dot(z,kz)+phi-dot(rhs,z),factor=1;bool accepted=false;for(int back=0;back<24;++back){V trial=z;for(int n=0;n<N;++n)trial[n]-=factor*step[n];double trialEnergy=.5*quad(K,trial)+potential(trial)-dot(rhs,trial);if(trialEnergy<=energy){z=trial;accepted=true;break;}factor*=.5;}if(!accepted)break;}
  return z;
 }
};
M correctedStringMass(const Model&m,int rate,bool naive){M a=m.Ms;double h=1.0/rate;for(int n=0;n<Q;++n){double omega=std::sqrt(m.old.stiffness[n]/m.m);if(!(omega>0&&omega<pi*rate))throw std::runtime_error("physical fixed mode above Nyquist");double mt=m.old.stiffness[n]*h*h/(4*std::pow(std::sin(.5*h*omega),2)),delta=mt-m.m;V v{};v[n]=1;if(!naive)v[Q]=m.d[n];for(int i=0;i<N;++i)for(int j=0;j<N;++j)at(a,i,j)+=delta*v[i]*v[j];}return a;}
struct Frame{V z{},v{},acc{};double bodyForce=0,stringForce=0,physicalAtState=0,directNumerical=0,point=0;};
struct Sav
{
 const Model&model;int rate;double h,lambda,gauge=1e-12,psi;M Msnum,Mn,Mni,ci{},di{};double activeEta=-1;bool activeBody=false;V z{},previous{},g{};double minPsi=1e100,minDen=1e100,maxDen=0,maxDrift=0;
 Sav(const Model&m,int fs,double regulator,bool naive=false):model(m),rate(fs),h(1.0/fs),lambda(regulator),Msnum(correctedStringMass(m,fs,naive)),Mn(Msnum){at(Mn,Q,Q)+=m.mb;Mni=inverse(Mn);auto w=generalEigen(m.mass,m.K);if(!(std::sqrt(w.back())<pi*rate))throw std::runtime_error("physical coupled mode above Nyquist");chol(add(Mn,m.K,-h*h/4));}
 void initialise(const V&q){z=q;V grad{};model.potential(z,&grad);auto rhs=mv(model.K,z);for(int n=0;n<N;++n)rhs[n]+=grad[n];auto acc=mv(Mni,rhs);V midpoint{};for(int n=0;n<N;++n){previous[n]=z[n]-.5*h*h*acc[n];midpoint[n]=.5*(z[n]+previous[n]);}psi=std::sqrt(2*model.potential(midpoint)+gauge);minPsi=psi;}
 void setHistory(const V&q,const V&p){z=q;previous=p;V mid{};for(int n=0;n<N;++n)mid[n]=.5*(q[n]+p[n]);psi=std::sqrt(2*model.potential(mid)+gauge);minPsi=psi;}
 void damping(double eta,bool body){if(eta!=activeEta||body!=activeBody){activeEta=eta;activeBody=body;ci=model.damping(eta,body);di=inverse(add(Mn,ci,h/2));}}
 double stringEnergy()const{V v{};for(int n=0;n<N;++n)v[n]=(z[n]-previous[n])/h;return .5*quad(Msnum,v)+.5*dot(z,mv(model.Ks,previous))+.5*(psi*psi-gauge);}
 double bodyEnergy()const{return .5*model.mb*std::pow((z[Q]-previous[Q])/h,2)+.5*model.kb*z[Q]*previous[Q];}
 Frame step(double force,double eta,bool body){damping(eta,body);Frame f;f.z=z;V grad{},mid{};double phi=model.potential(z,&grad),truth=std::sqrt(2*phi+gauge),norm=0;for(int n=0;n<N;++n){g[n]=grad[n]/truth;mid[n]=.5*(z[n]+previous[n]);norm+=std::abs((z[n]-previous[n])/h);}double error=psi-std::sqrt(2*model.potential(mid)+gauge);maxDrift=std::max(maxDrift,std::abs(.5*(psi*psi-gauge)-model.potential(mid)));if(lambda>0&&norm>1e-16)for(int n=0;n<N;++n)g[n]-=lambda*error/norm*((z[n]>previous[n])-(z[n]<previous[n]));
  double beta=h*h/4,gp=dot(g,previous);auto mz=mv(Mn,z),mp=mv(Mn,previous),cp=mv(ci,previous),kz=mv(model.K,z);V rhs{};for(int n=0;n<N;++n)rhs[n]=2*mz[n]-mp[n]+h/2*cp[n]-h*h*kz[n]+beta*g[n]*(gp-4*psi)+h*h*model.b[n]*force;auto r=mv(di,rhs),ig=mv(di,g);double den=1+beta*dot(g,ig),rank=beta*dot(g,r)/den;minDen=std::min(minDen,den);maxDen=std::max(maxDen,den);V next{};double change=0;for(int n=0;n<N;++n){next[n]=r[n]-rank*ig[n];f.v[n]=(next[n]-previous[n])/(2*h);f.acc[n]=(next[n]-2*z[n]+previous[n])/(h*h);change+=.5*g[n]*(next[n]-previous[n]);}double nextPsi=psi+change,psiBar=.5*(psi+nextPsi);
  f.bodyForce=model.mb*f.acc[Q]+(body?model.cb:0)*f.v[Q]+model.kb*z[Q];auto ma=mv(Msnum,f.acc),cv=mv(model.damping(eta,false),f.v),ksz=mv(model.Ks,z);f.stringForce=model.b[Q]*force-ma[Q]-cv[Q]-ksz[Q]-g[Q]*psiBar;
  auto anum=model.acceleration(z,f.v,force,ci,Mni),aphys=model.acceleration(z,f.v,force,ci,model.Minv);f.directNumerical=model.mb*anum[Q]+(body?model.cb:0)*f.v[Q]+model.kb*z[Q];f.physicalAtState=model.mb*aphys[Q]+(body?model.cb:0)*f.v[Q]+model.kb*z[Q];f.point=model.pointForce(z);
  previous=z;z=next;psi=nextPsi;minPsi=std::min(minPsi,psi);return f;
 }
};
struct Rk4{
 const Model&model;V z{},v{};std::array<V,4> dz{},dv{};
 Rk4(const Model&m,const V&initial):model(m),z(initial){}
 void step(double t,double h,double eta,bool body,const std::function<double(double)>&input){M c=model.damping(eta,body);for(int stage=0;stage<4;++stage){double f=stage==0?0:(stage==3?1:.5);V q=z,w=v;for(int n=0;n<N;++n)if(stage){q[n]+=f*h*dz[stage-1][n];w[n]+=f*h*dv[stage-1][n];}dz[stage]=w;dv[stage]=model.acceleration(q,w,input(t+f*h),c,model.Minv);}for(int n=0;n<N;++n){z[n]+=h/6*(dz[0][n]+2*dz[1][n]+2*dz[2][n]+dz[3][n]);v[n]+=h/6*(dv[0][n]+2*dv[1][n]+2*dv[2][n]+dv[3][n]);}}
 Frame frame(double force,double eta,bool body)const{Frame f;f.z=z;f.v=v;M c=model.damping(eta,body);f.acc=model.acceleration(z,v,force,c,model.Minv);f.bodyForce=model.mb*f.acc[Q]+(body?model.cb:0)*v[Q]+model.kb*z[Q];V grad{};model.potential(z,&grad);auto a=mv(model.Ms,f.acc),d=mv(model.damping(eta,false),v),k=mv(model.Ks,z);f.stringForce=model.b[Q]*force-a[Q]-d[Q]-k[Q]-grad[Q];f.point=model.pointForce(z);return f;}
};
struct Error{
 double q=0,qn=0,v=0,vn=0,y=0,yn=0,vy=0,vyn=0,f=0,fn=0;
 void add(const Frame&a,const Frame&b){for(int n=0;n<N;++n){q+=std::pow(a.z[n]-b.z[n],2);qn+=b.z[n]*b.z[n];v+=std::pow(a.v[n]-b.v[n],2);vn+=b.v[n]*b.v[n];}y+=std::pow(a.z[Q]-b.z[Q],2);yn+=b.z[Q]*b.z[Q];vy+=std::pow(a.v[Q]-b.v[Q],2);vyn+=b.v[Q]*b.v[Q];f+=std::pow(a.bodyForce-b.bodyForce,2);fn+=b.bodyForce*b.bodyForce;}
 std::array<double,5> values()const{return {std::sqrt(q/std::max(qn,1e-30)),std::sqrt(v/std::max(vn,1e-30)),std::sqrt(y/std::max(yn,1e-30)),std::sqrt(vy/std::max(vyn,1e-30)),std::sqrt(f/std::max(fn,1e-30))};}
 std::string fields()const{auto a=values();return "\"q_error\":"+num(a[0])+",\"v_error\":"+num(a[1])+",\"y_error\":"+num(a[2])+",\"vy_error\":"+num(a[3])+",\"port_force_error\":"+num(a[4]);}
};
struct Gap{double sq=0,ref=0,sum=0,peak=0;int count=0;void add(double a,double b){double d=a-b;sq+=d*d;ref+=b*b;sum+=d;peak=std::max(peak,std::abs(d));++count;}std::string json()const{return "{\"rms_n\":"+num(std::sqrt(sq/std::max(count,1)))+",\"mean_n\":"+num(sum/std::max(count,1))+",\"peak_n\":"+num(peak)+",\"relative_rms\":"+num(std::sqrt(sq/std::max(ref,1e-30)))+"}";}};
double pulse(double t){double f=0;for(double start:{.05,.10,.15}){double local=t-start;if(local>=0&&local<.001)f+=.5*(1-std::cos(2*pi*local/.001));}return f;}
struct Case{std::string name;bool nonlinear,driven;double seconds;V initial;};
struct Reference{std::vector<Frame> fine;Error self;double finalPhysicalEnergy=0;};
Reference makeReference(const Model&m,const Case&c){Reference r;constexpr int base=48000;int count=static_cast<int>(base*c.seconds);r.fine.resize(count);auto input=c.driven?std::function<double(double)>(pulse):std::function<double(double)>([](double){return 0.0;});for(int rate:{768000,384000}){Rk4 rk(m,c.initial);int ratio=rate/base,frames=count*ratio;for(int n=0;n<frames;++n){double t=double(n)/rate,eta=c.driven?(n>=rate/5?100:1):0;if(n%ratio==0){auto f=rk.frame(input(t),eta,c.driven);if(rate==768000)r.fine[n/ratio]=f;else r.self.add(f,r.fine[n/ratio]);}rk.step(t,1.0/rate,eta,c.driven,input);}if(rate==768000)r.finalPhysicalEnergy=m.physicalEnergy(rk.z,rk.v);}return r;}

// Independent work accumulation also covers the purely algebraic/linear loops.
struct LedgerMonitor{
 Sav&solver;double es0,eb0,e0,win=0,winAbs=0,ps=0,pb=0,ds=0,db=0,sabs=0,babs=0,joint=0,stringError=0,bodyError=0,mismatch=0,peak=0;
 explicit LedgerMonitor(Sav&s):solver(s),es0(s.stringEnergy()),eb0(s.bodyEnergy()),e0(es0+eb0){}
 void add(const Frame&f,double force,double eta,bool body){const auto&m=solver.model;double h=solver.h,wi=h*force*dot(m.b,f.v),wsp=h*f.stringForce*f.v[Q],wbp=h*f.bodyForce*f.v[Q],wsd=h*quad(m.damping(eta,false),f.v),wbd=h*(body?m.cb:0)*f.v[Q]*f.v[Q];win+=wi;winAbs+=std::abs(wi);ps+=wsp;pb+=wbp;ds+=wsd;db+=wbd;sabs+=std::abs(wi)+std::abs(wsp)+wsd;babs+=std::abs(wbp)+wbd;double es=solver.stringEnergy(),eb=solver.bodyEnergy();joint=std::max(joint,std::abs(es+eb-e0-win+ds+db)/std::max(std::abs(e0)+winAbs,1e-18));stringError=std::max(stringError,std::abs(es-es0-win+ps+ds)/std::max(std::abs(es0)+sabs,1e-18));bodyError=std::max(bodyError,std::abs(eb-eb0-pb+db)/std::max(std::abs(eb0)+babs,1e-18));mismatch=std::max(mismatch,std::abs(f.bodyForce-f.stringForce));peak=std::max({peak,std::abs(f.bodyForce),std::abs(f.stringForce)});}
 void finish(experiment::Audit&a,const std::string&name){bool pass=joint<1e-8&&stringError<1e-8&&bodyError<1e-8&&mismatch/std::max(peak,1e-30)<1e-10&&solver.minPsi>=0&&solver.minDen>=1;a.check(pass,"additional stepped-case work or domain gate");a.add("\"test\":\"additional_ledger\",\"case\":\""+name+"\",\"rate\":"+std::to_string(solver.rate)+",\"joint_balance\":"+num(joint)+",\"string_balance\":"+num(stringError)+",\"body_balance\":"+num(bodyError)+",\"branch_force_peak_error_n\":"+num(mismatch)+",\"force_peak_n\":"+num(peak)+",\"minimum_psi\":"+num(solver.minPsi)+",\"minimum_denominator\":"+num(solver.minDen));}
};

struct TrialResult{Error error;double joint=0,stringBalance=0,bodyBalance=0,forceMismatch=0,forcePeak=0;};
TrialResult trajectory(experiment::Audit&a,const Model&m,const Case&c,const Reference*ref,int rate,double lambda,bool naive=false){Sav s(m,rate,lambda,naive);s.initialise(c.initial);double es0=s.stringEnergy(),eb0=s.bodyEnergy(),e0=es0+eb0,win=0,winAbs=0,wps=0,wpb=0,wds=0,wdb=0,wsAbs=0,wbAbs=0;Gap aux,mass,space;TrialResult result;int frames=static_cast<int>(rate*c.seconds),ratio=rate/48000;for(int n=0;n<frames;++n){double t=double(n)/rate,force=c.driven?pulse(t):0,eta=c.driven?(n>=rate/5?100:1):0;auto f=s.step(force,eta,c.driven);double wi=s.h*force*dot(m.b,f.v),ps=s.h*f.stringForce*f.v[Q],pb=s.h*f.bodyForce*f.v[Q],ds=s.h*quad(m.damping(eta,false),f.v),db=s.h*(c.driven?m.cb:0)*f.v[Q]*f.v[Q];win+=wi;winAbs+=std::abs(wi);wps+=ps;wpb+=pb;wds+=ds;wdb+=db;wsAbs+=std::abs(wi)+std::abs(ps)+ds;wbAbs+=std::abs(pb)+db;double es=s.stringEnergy(),eb=s.bodyEnergy(),norm=std::max(std::abs(e0)+winAbs,1e-18);result.joint=std::max(result.joint,std::abs(es+eb-e0-win+wds+wdb)/norm);result.stringBalance=std::max(result.stringBalance,std::abs(es-es0-win+wps+wds)/std::max(std::abs(es0)+wsAbs,1e-18));result.bodyBalance=std::max(result.bodyBalance,std::abs(eb-eb0-wpb+wdb)/std::max(std::abs(eb0)+wbAbs,1e-18));result.forceMismatch=std::max(result.forceMismatch,std::abs(f.bodyForce-f.stringForce));result.forcePeak=std::max({result.forcePeak,std::abs(f.bodyForce),std::abs(f.stringForce)});if(n%ratio==0){if(ref)result.error.add(f,ref->fine[n/ratio]);aux.add(f.bodyForce,f.directNumerical);mass.add(f.directNumerical,f.physicalAtState);if(ref)space.add(ref->fine[n/ratio].bodyForce,ref->fine[n/ratio].point);}if(!std::isfinite(es+eb+s.psi))throw std::runtime_error("nonfinite candidate trajectory");}
 a.check(result.joint<1e-8&&result.stringBalance<1e-8&&result.bodyBalance<1e-8,"joint or branch power ledger gate");a.check(result.forceMismatch/std::max(result.forcePeak,1e-30)<1e-10,"independent branch reaction gate");a.check(s.minPsi>=0&&s.minDen>=1,"auxiliary sign or rank denominator gate");
 Sav observation=s;auto end=observation.step(c.driven?pulse(c.seconds):0,c.driven?100:0,c.driven);
 a.add("\"test\":\"trajectory\",\"case\":\""+c.name+"\",\"rate\":"+std::to_string(rate)+",\"lambda\":"+num(lambda)+",\"naive_control\":"+(naive?"true":"false")+","+(ref?result.error.fields():"\"q_error\":null,\"v_error\":null,\"y_error\":null,\"vy_error\":null,\"port_force_error\":null")+",\"joint_balance\":"+num(result.joint)+",\"string_balance\":"+num(result.stringBalance)+",\"body_balance\":"+num(result.bodyBalance)+",\"port_branch_peak_error_n\":"+num(result.forceMismatch)+",\"port_force_peak_n\":"+num(result.forcePeak)+",\"minimum_psi\":"+num(s.minPsi)+",\"minimum_denominator\":"+num(s.minDen)+",\"maximum_denominator\":"+num(s.maxDen)+",\"maximum_phi_drift_j\":"+num(s.maxDrift)+",\"input_work_j\":"+num(win)+",\"string_port_work_j\":"+num(wps)+",\"body_port_work_j\":"+num(wpb)+",\"string_dissipation_j\":"+num(wds)+",\"body_dissipation_j\":"+num(wdb)+",\"initial_numerical_energy_j\":"+num(e0)+",\"initial_physical_energy_j\":"+num(m.physicalEnergy(c.initial,V{}))+",\"final_numerical_energy_j\":"+num(s.stringEnergy()+s.bodyEnergy())+",\"final_physical_state_energy_j\":"+num(m.physicalEnergy(end.z,end.v))+",\"reference_final_physical_energy_j\":"+(ref?num(ref->finalPhysicalEnergy):"null")+",\"sav_force_gap\":"+aux.json()+",\"numerical_mass_force_gap\":"+mass.json()+",\"physical_weak_vs_point_gap\":"+(ref?space.json():"null"));return result;}

void algebra(experiment::Audit&a){Model linear(false),exact(true);a.add("\"test\":\"physical_matrices\",\"Ms\":"+mat(linear.Ms)+",\"M\":"+mat(linear.mass)+",\"Ks\":"+mat(linear.Ks)+",\"K\":"+mat(linear.K)+",\"C_eta1\":"+mat(linear.damping(1,true))+",\"b\":"+vec(linear.b)+",\"d\":"+vec(linear.d));
 for(double amplitude:{1e-7,1e-4,.004}){V z=exact.pluck(amplitude),direction{},grad{};z[Q]=amplitude/10;for(int n=0;n<N;++n)direction[n]=std::cos(.73*n)/(n+1);exact.potential(z,&grad);double h=amplitude*1e-5;V above=z,below=z;for(int n=0;n<N;++n){above[n]+=h*direction[n];below[n]-=h*direction[n];}double predicted=dot(grad,direction),finite=(exact.potential(above)-exact.potential(below))/(2*h),err=std::abs(finite-predicted)/std::max(std::abs(predicted),1e-30);a.check(err<1e-6,"full lifted potential gradient gate");a.add("\"test\":\"gradient\",\"amplitude_m\":"+num(amplitude)+",\"relative_error\":"+num(err));}
 for(int rate:{48000,96000,192000}){double h=1.0/rate;M ms=correctedStringMass(linear,rate,false),mn=ms;at(mn,Q,Q)+=linear.mb;M naive=correctedStringMass(linear,rate,true);auto evMs=eigenvalues(linear.Ms),evM=eigenvalues(linear.mass),evMsnum=eigenvalues(ms),evMn=eigenvalues(mn),coercive=eigenvalues(add(mn,linear.K,-h*h/4)),stringCoercive=eigenvalues(add(ms,linear.Ks,-h*h/4)),physical=generalEigen(linear.mass,linear.K),numerical=generalEigen(mn,linear.K);a.check(evMs[0]>0&&evM[0]>0&&evMsnum[0]>0&&evMn[0]>0&&coercive[0]>0,"mass or full ledger coercivity gate");a.check(std::sqrt(physical.back())<pi*rate,"physical coupled Nyquist gate");double bodyCoercivity=linear.mb-h*h*linear.kb/4;a.check(bodyCoercivity>0,"body ledger coercivity gate");V cents{};for(int n=0;n<N;++n)cents[n]=1200*std::log2((2/h)*std::asin(.5*h*std::sqrt(numerical[n]))/std::sqrt(physical[n]));a.add("\"test\":\"mass_and_coercivity\",\"rate\":"+std::to_string(rate)+",\"Msnum\":"+mat(ms)+",\"Msnaive\":"+mat(naive)+",\"physical_Ms_eigenvalues\":"+vec(evMs)+",\"physical_M_eigenvalues\":"+vec(evM)+",\"numerical_Ms_eigenvalues\":"+vec(evMsnum)+",\"numerical_M_eigenvalues\":"+vec(evMn)+",\"joint_coercivity_eigenvalues\":"+vec(coercive)+",\"string_coercivity_eigenvalues\":"+vec(stringCoercive)+",\"body_coercivity_kg\":"+num(bodyCoercivity)+",\"coupled_pole_cents\":"+vec(cents));
  for(int mode=0;mode<Q;++mode){V q{},v{},acc{};q[mode]=.001;v[mode]=.01;double target=linear.d[mode]*linear.old.stiffness[mode]*q[mode],correct=-at(ms,Q,mode)*(-linear.old.stiffness[mode]*q[mode]/at(ms,mode,mode)),bad=-at(naive,Q,mode)*(-linear.old.stiffness[mode]*q[mode]/at(naive,mode,mode)),err=std::abs(correct/target-1),badError=bad/target-1,pred=linear.m/at(ms,mode,mode)-1;double force=.01,eta=1;for(int n=0;n<Q;++n)acc[n]=(linear.b[n]*force-2*eta*linear.m*v[n]-linear.old.stiffness[n]*q[n])/at(ms,n,n);double actual=linear.b[Q]*force;for(int n=0;n<Q;++n)actual-=at(ms,Q,n)*acc[n]+2*eta*linear.m*linear.d[n]*v[n];double forcedTarget=(linear.b[Q]-dot(linear.d,linear.b))*force+target;double forcedError=std::abs(actual-forcedTarget)/std::max(std::abs(forcedTarget),1e-30);a.check(err<1e-12&&forcedError<1e-12,"fixed-boundary physical reaction identity gate");a.check(std::abs(badError-pred)<1e-12,"naive reaction differs from predicted bias");if(rate==48000&&mode==Q-1)a.check(std::abs(badError)>1e-3,"naive top-mode reaction control lost sensitivity");a.add("\"test\":\"fixed_linear_reaction\",\"rate\":"+std::to_string(rate)+",\"mode\":"+std::to_string(mode+1)+",\"corrected_relative_error\":"+num(err)+",\"naive_relative_bias\":"+num(badError)+",\"forced_damped_identity_error\":"+num(forcedError));}
  for(double amplitude:{.001,.004})for(double lambda:{0.0,1000.0}){V z=exact.pluck(amplitude),grad{},previous{},mid{},g{},next{};exact.potential(z,&grad);double norm=0;for(int n=0;n<Q;++n){previous[n]=z[n]-.5*h*h*(exact.old.stiffness[n]*z[n]+grad[n])/at(ms,n,n);mid[n]=.5*(z[n]+previous[n]);norm+=std::abs((z[n]-previous[n])/h);}double psi=std::sqrt(2*exact.potential(mid)+1e-12),truth=std::sqrt(2*exact.potential(z)+1e-12),drift=psi-std::sqrt(2*exact.potential(mid)+1e-12);for(int n=0;n<N;++n){g[n]=grad[n]/truth;if(lambda&&norm>1e-16)g[n]-=lambda*drift/norm*((z[n]>previous[n])-(z[n]<previous[n]));}double beta=h*h/4,gp=dot(g,previous),den=1,gr=0;for(int n=0;n<Q;++n){next[n]=(2*at(ms,n,n)*z[n]-at(ms,n,n)*previous[n]-h*h*exact.old.stiffness[n]*z[n]+beta*g[n]*(gp-4*psi))/at(ms,n,n);gr+=g[n]*next[n];den+=beta*g[n]*g[n]/at(ms,n,n);}for(int n=0;n<Q;++n)next[n]-=beta*g[n]/at(ms,n,n)*gr/den;double change=0;for(int n=0;n<Q;++n)change+=.5*g[n]*(next[n]-previous[n]);double fsav=0,fweak=0;for(int n=0;n<Q;++n){fsav+=exact.d[n]*exact.old.stiffness[n]*z[n];fweak+=exact.d[n]*(exact.old.stiffness[n]*z[n]+grad[n]);}fsav+=(dot(exact.d,g)-g[Q])*(psi+.5*change);fweak-=grad[Q];a.add("\"test\":\"fixed_nonlinear_force_split\",\"rate\":"+std::to_string(rate)+",\"amplitude_m\":"+num(amplitude)+",\"lambda\":"+num(lambda)+",\"weak_force_n\":"+num(fweak)+",\"sav_force_n\":"+num(fsav)+",\"point_force_n\":"+num(exact.pointForce(z)));}
 }
 // Exact zero and odd sign symmetry at all declared rates; pulse sign reverses.
 for(int rate:{48000,96000,192000}){Sav zero(exact,rate,1000),pos(exact,rate,1000),neg(exact,rate,1000);zero.initialise(V{});auto q=exact.pluck(.004);pos.initialise(q);for(auto&x:q)x=-x;neg.initialise(q);LedgerMonitor zl(zero),pl(pos),nl(neg);double maxQ=0,maxF=0,maxPsi=0;for(int n=0;n<rate/10;++n){double t=double(n)/rate;auto zf=zero.step(0,1,true);auto p=pos.step(pulse(t),1,true),m=neg.step(-pulse(t),1,true);zl.add(zf,0,1,true);pl.add(p,pulse(t),1,true);nl.add(m,-pulse(t),1,true);for(int j=0;j<N;++j)maxQ=std::max(maxQ,std::abs(p.z[j]+m.z[j]));maxF=std::max(maxF,std::abs(p.bodyForce+m.bodyForce));maxPsi=std::max(maxPsi,std::abs(pos.psi-neg.psi));}zl.finish(a,"zero");pl.finish(a,"positive-symmetry");nl.finish(a,"negative-symmetry");a.check(dot(zero.z,zero.z)==0,"exact zero-state gate");a.check(maxQ<1e-14&&maxF<1e-10&&maxPsi<1e-12,"odd signed symmetry gate");a.add("\"test\":\"zero_and_symmetry\",\"rate\":"+std::to_string(rate)+",\"zero_squared_displacement\":"+num(dot(zero.z,zero.z))+",\"maximum_q_sum_m\":"+num(maxQ)+",\"maximum_force_sum_n\":"+num(maxF)+",\"maximum_psi_difference\":"+num(maxPsi));}
}

struct Transfer{CV z;std::complex<double>compliance,mobility,endpointDisplacement,endpointVelocity,bodyForce;};
Transfer transfer(const Model&m,int rate,double frequency,bool numerical){double h=1.0/rate,w=2*pi*frequency;M mass=m.mass;if(numerical){mass=correctedStringMass(m,rate,false);at(mass,Q,Q)+=m.mb;}M c=m.damping(1,true);double acceleration=numerical?4*std::pow(std::sin(w*h/2),2)/(h*h):w*w,velocity=numerical?std::sin(w*h)/h:w;CM a{};CV b{};for(int i=0;i<N;++i){b[i]=m.b[i];for(int j=0;j<N;++j)a[i*N+j]=at(m.K,i,j)-acceleration*at(mass,i,j)+std::complex<double>(0,velocity*at(c,i,j));}Transfer t;t.z=solveComplex(a,b);for(int n=0;n<N;++n)t.compliance+=m.b[n]*t.z[n];t.mobility=std::complex<double>(0,velocity)*t.compliance;t.endpointDisplacement=t.z[Q];t.endpointVelocity=std::complex<double>(0,velocity)*t.z[Q];t.bodyForce=(m.kb-m.mb*acceleration+std::complex<double>(0,m.cb*velocity))*t.z[Q];return t;}
void linearDrive(experiment::Audit&a){Model m(false);std::array<double,2>previous{};for(int rate:{48000,96000,192000}){V staticQ=solveChol(chol(m.K),m.b);for(auto&x:staticQ)x*=.01;Sav stat(m,rate,1000);stat.setHistory(staticQ,staticQ);LedgerMonitor staticLedger(stat);double staticError=0;for(int n=0;n<rate/10;++n){auto f=stat.step(.01,1,true);staticLedger.add(f,.01,1,true);double e=0,r=0;for(int j=0;j<N;++j){e+=std::pow(f.z[j]-staticQ[j],2);r+=staticQ[j]*staticQ[j];}staticError=std::max(staticError,std::sqrt(e/r));}staticLedger.finish(a,"static-point-load");a.check(staticError<1e-8,"full physical static compliance gate");a.add("\"test\":\"static_compliance\",\"rate\":"+std::to_string(rate)+",\"relative_error\":"+num(staticError));
 double errorH=0,normH=0,errorY=0,normY=0,maxH=0,maxHerr=0,maxY=0,maxYerr=0;for(double frequency:{80.0,196.0099263900649,220.0,440.0,1000.0,2000.0,3000.0}){auto phys=transfer(m,rate,frequency,false),numeric=transfer(m,rate,frequency,true);errorH+=std::norm(numeric.compliance-phys.compliance);normH+=std::norm(phys.compliance);errorY+=std::norm(numeric.mobility-phys.mobility);normY+=std::norm(phys.mobility);maxH=std::max(maxH,std::abs(phys.compliance));maxHerr=std::max(maxHerr,std::abs(numeric.compliance-phys.compliance));maxY=std::max(maxY,std::abs(phys.mobility));maxYerr=std::max(maxYerr,std::abs(numeric.mobility-phys.mobility));Sav s(m,rate,1000);V initial{},history{};for(int n=0;n<N;++n){initial[n]=.01*numeric.z[n].real();history[n]=.01*(numeric.z[n]*std::exp(std::complex<double>(0,-2*pi*frequency/rate))).real();}s.setHistory(initial,history);LedgerMonitor sinusoidLedger(s);double error=0,norm=0;for(int n=0;n<rate/10;++n){double t=double(n)/rate;auto phase=std::exp(std::complex<double>(0,2*pi*frequency*t));auto f=s.step(.01*phase.real(),1,true);sinusoidLedger.add(f,.01*phase.real(),1,true);for(int j=0;j<N;++j){double expected=.01*(numeric.z[j]*phase).real();error+=std::pow(f.z[j]-expected,2);norm+=expected*expected;}}sinusoidLedger.finish(a,"sinusoid-"+num(frequency)+"Hz");double relative=std::sqrt(error/norm);a.check(relative<1e-8,"driven linear recurrence versus resolvent gate");a.add("\"test\":\"complex_transfer\",\"rate\":"+std::to_string(rate)+",\"frequency_hz\":"+num(frequency)+",\"physical_compliance\":"+complexJson(phys.compliance)+",\"numerical_compliance\":"+complexJson(numeric.compliance)+",\"physical_mobility\":"+complexJson(phys.mobility)+",\"numerical_mobility\":"+complexJson(numeric.mobility)+",\"physical_endpoint_displacement\":"+complexJson(phys.endpointDisplacement)+",\"numerical_endpoint_displacement\":"+complexJson(numeric.endpointDisplacement)+",\"physical_endpoint_velocity\":"+complexJson(phys.endpointVelocity)+",\"numerical_endpoint_velocity\":"+complexJson(numeric.endpointVelocity)+",\"physical_body_force\":"+complexJson(phys.bodyForce)+",\"numerical_body_force\":"+complexJson(numeric.bodyForce)+",\"recurrence_resolvent_error\":"+num(relative));}
 std::array<double,2>current{std::sqrt(errorH/normH),std::sqrt(errorY/normY)};if(rate==48000)a.check(current[0]<.02&&current[1]<.02,"48k complex physical compliance or mobility gate");else a.check(current[0]<previous[0]/3&&current[1]<previous[1]/3,"complex physical response convergence gate");previous=current;a.add("\"test\":\"complex_transfer_aggregate\",\"rate\":"+std::to_string(rate)+",\"compliance_error\":"+num(current[0])+",\"mobility_error\":"+num(current[1])+",\"max_compliance_error_over_max_reference\":"+num(maxHerr/maxH)+",\"max_mobility_error_over_max_reference\":"+num(maxYerr/maxY));}}

bool linearReferenceCheck(experiment::Audit&a){Model m(false);bool passed=true;for(double frequency:{220.0,2000.0})for(int rate:{384000,768000}){auto phys=transfer(m,rate,frequency,false);V initial{};for(int n=0;n<N;++n)initial[n]=.01*phys.z[n].real();Rk4 rk(m,initial);for(int n=0;n<N;++n)rk.v[n]=.01*(std::complex<double>(0,2*pi*frequency)*phys.z[n]).real();double error=0,norm=0,ve=0,vnorm=0;for(int n=0;n<rate/10;++n){double t=double(n)/rate;auto phase=std::exp(std::complex<double>(0,2*pi*frequency*t));for(int j=0;j<N;++j){double z=.01*(phys.z[j]*phase).real(),v=.01*(std::complex<double>(0,2*pi*frequency)*phys.z[j]*phase).real();error+=std::pow(rk.z[j]-z,2);norm+=z*z;ve+=std::pow(rk.v[j]-v,2);vnorm+=v*v;}rk.step(t,1.0/rate,1,true,[frequency](double time){return .01*std::cos(2*pi*frequency*time);});}double q=std::sqrt(error/norm),v=std::sqrt(ve/vnorm);bool ok=q<1e-6&&v<1e-5;passed&=ok;a.check(ok,"physical RK4 versus exact driven linear solution gate");a.add("\"test\":\"linear_physical_reference\",\"frequency_hz\":"+num(frequency)+",\"rate\":"+std::to_string(rate)+",\"q_error\":"+num(q)+",\"v_error\":"+num(v));}return passed;}

int run(const std::filesystem::path&out){if(!std::filesystem::create_directory(out))throw std::runtime_error("output directory must be new");experiment::Audit a(out/"report.json");try{
 std::cout<<"Algebra, PSD, force identities and symmetry...\n"<<std::flush;algebra(a);if(a.failures){a.add("\"status\":\"stopped_after_algebra_failure\"");a.finish();return 1;}
 std::cout<<"Independent physical reference gates...\n"<<std::flush;if(!linearReferenceCheck(a)){a.add("\"status\":\"stopped_after_linear_reference_failure\"");a.finish();return 1;}
 std::vector<Case>cases;std::vector<Reference>references;for(bool nonlinear:{false,true}){Model m(nonlinear);std::string prefix=nonlinear?"exact":"linear";cases.push_back({prefix+"-gaussian4mm",nonlinear,false,.1,m.pluck(.004)});for(double force:{.25,1.0}){int iterations=0;double residual=0,minH=0;auto z=m.equilibrium(force,iterations,residual,minH);a.check(residual<1e-12&&minH>0,"loaded equilibrium residual or Hessian gate");a.add("\"test\":\"loaded_equilibrium\",\"model\":\""+prefix+"\",\"force_n\":"+num(force)+",\"iterations\":"+std::to_string(iterations)+",\"relative_force_residual\":"+num(residual)+",\"minimum_hessian_eigenvalue\":"+num(minH)+",\"z\":"+vec(z));cases.push_back({prefix+"-equilibrium"+num(force)+"N",nonlinear,false,.1,z});}}
 Model exact(true);cases.push_back({"exact-driven-release",true,true,.4,exact.pluck(.002)});if(a.failures){a.add("\"status\":\"stopped_after_equilibrium_failure\"");a.finish();return 1;}
 for(const auto&c:cases){std::cout<<"Reference "<<c.name<<"...\n"<<std::flush;Model m(c.nonlinear);auto r=makeReference(m,c);auto e=r.self.values();bool ok=e[0]<1e-6&&e[1]<1e-5&&e[4]<1e-5;a.check(ok,"physical RK4 self-convergence gate");a.add("\"test\":\"reference_self_convergence\",\"case\":\""+c.name+"\",\"rates\":[384000,768000],"+r.self.fields()+",\"final_physical_energy_j\":"+num(r.finalPhysicalEnergy));references.push_back(std::move(r));if(!ok){a.add("\"status\":\"stopped_after_reference_self_convergence_failure\"");a.finish();return 1;}}
 std::cout<<"Qualified-reference candidate trajectories...\n"<<std::flush;for(std::size_t i=0;i<cases.size();++i){const auto&c=cases[i];Model m(c.nonlinear);for(double lambda:{1000.0,0.0}){if(!c.nonlinear&&lambda==0)continue;std::array<double,5>previous{};for(int rate:{48000,96000,192000}){auto r=trajectory(a,m,c,&references[i],rate,lambda);auto errors=r.error.values(),floor=references[i].self.values();if(lambda==1000){if(rate==48000)a.check(errors[0]<.01&&errors[1]<.01&&errors[2]<.01&&errors[3]<.01&&errors[4]<.02,"48k candidate physical state or port error gate");else{bool passed=true;std::string limited="[";for(int n=0;n<5;++n){bool referenceLimited=errors[n]<=10*floor[n];if(!referenceLimited&&!(errors[n]<previous[n]/3))passed=false;limited+=(n?",":"")+std::string(referenceLimited?"true":"false");}a.check(passed,"candidate sample-rate convergence gate");a.add("\"test\":\"convergence_reference_limits\",\"case\":\""+c.name+"\",\"rate\":"+std::to_string(rate)+",\"reference_limited_q_v_y_vy_force\":"+limited+"]");}}previous=errors;}}}
 Case naive{"linear-gaussian4mm-naive-control",false,false,.1,Model(false).pluck(.004)};Model linear(false);trajectory(a,linear,naive,nullptr,48000,1000,true);
 std::cout<<"Driven physical compliance and numerical resolvents...\n"<<std::flush;linearDrive(a);a.add("\"status\":\"completed_all_declared_stages\"");a.finish();std::cout<<"Moving-port audit failures: "<<a.failures<<'\n';return a.failures?1:0;
 }catch(const std::exception&e){a.check(false,e.what());a.add("\"status\":\"stopped_after_exception\"");a.finish();return 1;}}
} // namespace port
int main(int argc,char**argv){if(argc!=2){std::cerr<<"usage: MovingPortAudit NEW_OUTPUT_DIRECTORY\n";return 2;}try{return port::run(argv[1]);}catch(const std::exception&e){std::cerr<<e.what()<<'\n';return 2;}}
